import type { StyleVars } from '../utils/styleVars'

const md3Light = {
  "--action-sheet-action-item-color": "#1D1B20",
  "--action-sheet-background": "var(--color-surface-container-high)",
  "--action-sheet-border-radius": "0px",
  "--action-sheet-title-color": "var(--color-on-surface-variant)",
  "--alert-border-radius": "4px",
  "--alert-close-icon-margin": "2px 0 0 12px",
  "--alert-close-icon-size": "22px",
  "--alert-danger-background": "var(--color-danger)",
  "--alert-icon-margin": "0 12px 0 0",
  "--alert-icon-size": "22px",
  "--alert-info-background": "var(--color-info)",
  "--alert-message-font-size": "14px",
  "--alert-message-line-height": "1.5",
  "--alert-message-margin-top": "4px",
  "--alert-padding": "16px",
  "--alert-standard-danger-text-color": "var(--color-on-danger)",
  "--alert-standard-info-text-color": "var(--color-on-info)",
  "--alert-standard-success-text-color": "var(--color-on-success)",
  "--alert-standard-warning-text-color": "var(--color-on-warning)",
  "--alert-success-background": "var(--color-success)",
  "--alert-title-font-size": "16px",
  "--alert-title-font-weight": "500",
  "--alert-title-line-height": "1.5",
  "--alert-tonal-danger-background": "hsla(var(--hsl-danger), 0.12)",
  "--alert-tonal-danger-text-color": "var(--color-danger)",
  "--alert-tonal-info-background": "hsla(var(--hsl-info), 0.12)",
  "--alert-tonal-info-text-color": "var(--color-info)",
  "--alert-tonal-success-background": "hsla(var(--hsl-success), 0.12)",
  "--alert-tonal-success-text-color": "var(--color-success)",
  "--alert-tonal-warning-background": "hsla(var(--hsl-warning), 0.12)",
  "--alert-tonal-warning-text-color": "var(--color-warning)",
  "--alert-warning-background": "var(--color-warning)",
  "--app-bar-border-bottom": "thin solid var(--color-outline)",
  "--app-bar-border-radius": "4px",
  "--app-bar-color": "var(--color-primary)",
  "--app-bar-font-size": "var(--font-size-lg)",
  "--app-bar-height": "54px",
  "--app-bar-left-gap": "6px",
  "--app-bar-right-gap": "6px",
  "--app-bar-text-color": "#fff",
  "--app-bar-title-font-size": "var(--font-size-lg)",
  "--app-bar-title-padding": "0 12px",
  "--avatar-background-color": "var(--color-primary)",
  "--avatar-group-offset": "-10px",
  "--avatar-text-color": "#fff",
  "--back-top-bottom": "40px",
  "--back-top-button-border-radius": "12px",
  "--back-top-button-size": "40px",
  "--back-top-right": "40px",
  "--badge-content-border": "none",
  "--badge-content-border-radius": "100px",
  "--badge-content-font-size": "12px",
  "--badge-content-padding": "2px 6px",
  "--badge-danger-color": "var(--color-danger)",
  "--badge-danger-text-color": "var(--color-on-danger)",
  "--badge-default-color": "#e0e0e0",
  "--badge-default-text-color": "#1d1b20",
  "--badge-dot-height": "8px",
  "--badge-dot-width": "8px",
  "--badge-icon-size": "12px",
  "--badge-info-color": "var(--color-info)",
  "--badge-info-text-color": "var(--color-on-info)",
  "--badge-primary-color": "var(--color-primary)",
  "--badge-primary-text-color": "var(--color-on-primary)",
  "--badge-success-color": "var(--color-success)",
  "--badge-success-text-color": "var(--color-on-success)",
  "--badge-warning-color": "var(--color-warning)",
  "--badge-warning-text-color": "var(--color-on-warning)",
  "--bottom-navigation-background-color": "var(--color-surface-container)",
  "--bottom-navigation-border-color": "var(--color-outline)",
  "--bottom-navigation-fab-border-radius": "12px",
  "--bottom-navigation-fab-offset": "4px",
  "--bottom-navigation-height": "50px",
  "--bottom-navigation-item-active-background-color": "var(--color-info-container)",
  "--bottom-navigation-item-active-color": "var(--color-primary)",
  "--bottom-navigation-item-font-size": "var(--font-size-sm)",
  "--bottom-navigation-item-icon-margin-bottom": "5px",
  "--bottom-navigation-item-icon-size": "22px",
  "--bottom-navigation-item-inactive-color": "var(--color-on-surface-variant)",
  "--bottom-navigation-item-line-height": "1",
  "--bottom-navigation-item-variant-active-background-color": "var(--color-info-container)",
  "--bottom-navigation-item-variant-active-color": "var(--color-on-info-container)",
  "--bottom-navigation-item-variant-icon-container-border-radius": "100px",
  "--bottom-navigation-item-variant-icon-container-height": "30px",
  "--bottom-navigation-item-variant-icon-container-max-width": "58px",
  "--bottom-navigation-variant-height": "66px",
  "--bottom-navigation-z-index": "1",
  "--breadcrumb-active-color": "var(--color-primary)",
  "--breadcrumb-inactive-color": "var(--color-on-surface-variant)",
  "--breadcrumb-separator-font-size": "14px",
  "--breadcrumb-separator-margin": "0 10px",
  "--button-border-radius": "100px",
  "--button-danger-color": "var(--color-danger)",
  "--button-danger-icon-color": "var(--color-on-danger-container)",
  "--button-danger-icon-container-color": "var(--color-danger-container)",
  "--button-danger-text-color": "var(--color-on-danger)",
  "--button-default-color": "var(--color-surface-container-low)",
  "--button-default-icon-color": "var(--color-on-info-container)",
  "--button-default-icon-container-color": "var(--color-surface-container-high)",
  "--button-default-text-color": "var(--color-primary)",
  "--button-disabled-color": "var(--color-disabled)",
  "--button-disabled-text-color": "var(--color-text-disabled)",
  "--button-info-color": "var(--color-info)",
  "--button-info-icon-color": "var(--color-on-info-container)",
  "--button-info-icon-container-color": "var(--color-info-container)",
  "--button-info-text-color": "var(--color-on-info)",
  "--button-large-font-size": "var(--font-size-lg)",
  "--button-large-height": "44px",
  "--button-large-padding": "0 22px",
  "--button-mini-font-size": "var(--font-size-xs)",
  "--button-mini-height": "20px",
  "--button-mini-padding": "0 8px",
  "--button-normal-font-size": "var(--font-size-md)",
  "--button-normal-height": "36px",
  "--button-normal-padding": "0 16px",
  "--button-primary-color": "var(--color-primary)",
  "--button-primary-icon-color": "var(--color-on-primary-container)",
  "--button-primary-icon-container-color": "var(--color-primary-container)",
  "--button-primary-text-color": "var(--color-on-primary)",
  "--button-round-padding": "6px",
  "--button-small-font-size": "var(--font-size-sm)",
  "--button-small-height": "28px",
  "--button-small-padding": "0 12px",
  "--button-success-color": "var(--color-success)",
  "--button-success-icon-color": "var(--color-on-success-container)",
  "--button-success-icon-container-color": "var(--color-success-container)",
  "--button-success-text-color": "var(--color-on-success)",
  "--button-warning-color": "var(--color-warning)",
  "--button-warning-icon-color": "var(--color-on-warning-container)",
  "--button-warning-icon-container-color": "var(--color-warning-container)",
  "--button-warning-text-color": "var(--color-on-warning)",
  "--card-background": "var(--color-surface-container-low)",
  "--card-border-radius": "12px",
  "--card-close-button-border-radius": "12px",
  "--card-close-button-icon-size": "24px",
  "--card-close-button-primary-color": "var(--color-primary-container)",
  "--card-close-button-size": "56px",
  "--card-close-button-text-color": "var(--color-on-primary-container)",
  "--card-content-color": "var(--color-on-surface-variant)",
  "--card-content-font-size": "14px",
  "--card-content-margin": "16px 0 0 0",
  "--card-content-padding": "0 16px",
  "--card-content-row-margin": "16px 0 0 0",
  "--card-description-color": "var(--color-on-surface-variant)",
  "--card-description-font-size": "14px",
  "--card-description-margin": "32px 0 0 0",
  "--card-description-padding": "0 16px",
  "--card-filled-background": "var(--color-surface-container-highest)",
  "--card-floating-buttons-bottom": "16px",
  "--card-floating-buttons-color": "#fff",
  "--card-floating-buttons-right": "16px",
  "--card-footer-bottom": "9px",
  "--card-footer-margin": "32px 0 0 0",
  "--card-footer-padding": "0 16px",
  "--card-footer-right": "13px",
  "--card-image-height": "188px",
  "--card-image-width": "100%",
  "--card-line-height": "22px",
  "--card-outline-color": "var(--color-outline)",
  "--card-padding": "0 0 16px 0",
  "--card-row-height": "140px",
  "--card-row-image-width": "140px",
  "--card-row-line-height": "1.5",
  "--card-subtitle-color": "var(--color-on-surface-variant)",
  "--card-subtitle-font-size": "14px",
  "--card-subtitle-margin": "4px 0 0 0",
  "--card-subtitle-padding": "0 16px",
  "--card-subtitle-row-margin": "4px 0 0 0",
  "--card-title-color": "#1D1B20",
  "--card-title-font-size": "16px",
  "--card-title-margin": "16px 0 0 0",
  "--card-title-padding": "0 16px",
  "--card-title-row-margin": "16px 0 0 0",
  "--cell-border-color": "var(--color-outline)",
  "--cell-border-left": "12px",
  "--cell-border-right": "12px",
  "--cell-color": "var(--color-text)",
  "--cell-description-color": "var(--color-on-surface-variant)",
  "--cell-description-font-size": "var(--font-size-sm)",
  "--cell-description-margin-top": "4px",
  "--cell-extra-left": "8px",
  "--cell-font-size": "var(--font-size-md)",
  "--cell-icon-right": "8px",
  "--cell-min-height": "40px",
  "--cell-padding": "10px 12px",
  "--checkbox-action-padding": "6px",
  "--checkbox-checked-color": "var(--color-primary)",
  "--checkbox-disabled-color": "var(--color-text-disabled)",
  "--checkbox-error-color": "var(--color-danger)",
  "--checkbox-icon-size": "24px",
  "--checkbox-text-color": "var(--color-on-surface-variant)",
  "--checkbox-unchecked-color": "var(--color-on-surface-variant)",
  "--chip-border-radius": "2px",
  "--chip-danger-color": "var(--color-danger-container)",
  "--chip-danger-plain-color": "var(--color-danger)",
  "--chip-danger-text-color": "var(--color-on-danger-container)",
  "--chip-default-color": "var(--color-surface-container-high)",
  "--chip-default-text-color": "#1D192B",
  "--chip-info-color": "var(--color-info-container)",
  "--chip-info-plain-color": "var(--color-info)",
  "--chip-info-text-color": "var(--color-on-info-container)",
  "--chip-large-font-size": "var(--font-size-lg)",
  "--chip-large-height": "40px",
  "--chip-large-padding": "0 17px",
  "--chip-mini-font-size": "var(--font-size-xs)",
  "--chip-mini-height": "16px",
  "--chip-mini-padding": "0 4px",
  "--chip-normal-font-size": "var(--font-size-md)",
  "--chip-normal-height": "32px",
  "--chip-normal-padding": "0 10px",
  "--chip-primary-color": "var(--color-primary-container)",
  "--chip-primary-plain-color": "var(--color-primary)",
  "--chip-primary-text-color": "var(--color-on-primary-container)",
  "--chip-round-radius": "8px",
  "--chip-small-font-size": "var(--font-size-sm)",
  "--chip-small-height": "24px",
  "--chip-small-padding": "0 6px",
  "--chip-success-color": "var(--color-success-container)",
  "--chip-success-plain-color": "var(--color-success)",
  "--chip-success-text-color": "var(--color-on-success-container)",
  "--chip-text-large-margin": "0 5px",
  "--chip-text-mini-margin": "0 2px",
  "--chip-text-normal-margin": "0 5px",
  "--chip-text-small-margin": "0 3px",
  "--chip-warning-color": "var(--color-warning-container)",
  "--chip-warning-plain-color": "var(--color-warning)",
  "--chip-warning-text-color": "var(--color-on-warning-container)",
  "--code-font-size": "14px",
  "--code-line-height": "1.7",
  "--collapse-background": "var(--color-surface-container-low)",
  "--collapse-border-top": "thin solid var(--color-outline)",
  "--collapse-content-font-size": "var(--font-size-md)",
  "--collapse-content-padding": "0 12px 10px",
  "--collapse-disable-color": "#bdbdbd",
  "--collapse-header-font-size": "var(--font-size-lg)",
  "--collapse-header-padding": "10px 12px",
  "--collapse-item-margin-top": "16px",
  "--collapse-text-color": "#1D1B20",
  "--color-body": "hsla(var(--hsl-body), 1)",
  "--color-danger": "hsla(var(--hsl-danger), 1)",
  "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
  "--color-disabled": "hsla(var(--hsl-disabled), 1)",
  "--color-info": "hsla(var(--hsl-info), 1)",
  "--color-info-container": "hsla(var(--hsl-info-container), 1)",
  "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)",
  "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
  "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
  "--color-on-info": "hsla(var(--hsl-on-info), 1)",
  "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
  "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
  "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
  "--color-on-success": "hsla(var(--hsl-on-success), 1)",
  "--color-on-success-container": "hsla(var(--hsl-on-success-container), 1)",
  "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
  "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
  "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
  "--color-outline": "hsla(var(--hsl-outline), 1)",
  "--color-primary": "hsla(var(--hsl-primary), 1)",
  "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
  "--color-scheme": "light",
  "--color-success": "hsla(var(--hsl-success), 1)",
  "--color-success-container": "hsla(var(--hsl-success-container), 1)",
  "--color-surface-container": "hsla(var(--hsl-surface-container), 1)",
  "--color-surface-container-high": "hsla(var(--hsl-surface-container-high), 1)",
  "--color-surface-container-highest": "hsla(var(--hsl-surface-container-highest), 1)",
  "--color-surface-container-low": "hsla(var(--hsl-surface-container-low), 1)",
  "--color-text": "hsla(var(--hsl-text), 1)",
  "--color-text-disabled": "hsla(var(--hsl-text-disabled), 1)",
  "--color-warning": "hsla(var(--hsl-warning), 1)",
  "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
  "--countdown-text-color": "var(--color-text)",
  "--countdown-text-font-size": "var(--font-size-lg)",
  "--counter-background": "var(--color-primary)",
  "--counter-button-icon-size": "100%",
  "--counter-button-size": "28px",
  "--counter-button-text-color": "#fff",
  "--counter-disabled-color": "var(--color-disabled)",
  "--counter-disabled-opacity": "var(--opacity-disabled)",
  "--counter-error-color": "var(--color-danger)",
  "--counter-font-color": "#fff",
  "--counter-input-font-size": "14px",
  "--counter-input-margin": "0 4px",
  "--counter-input-width": "28px",
  "--counter-padding": "0 4px",
  "--cubic-bezier": "cubic-bezier(0.25, 0.8, 0.5, 1)",
  "--date-picker-actions-padding": "20px",
  "--date-picker-body-background-color": "var(--color-surface-container-high)",
  "--date-picker-body-height": "300px",
  "--date-picker-body-padding": "0 14px 16px",
  "--date-picker-border-radius": "20px",
  "--date-picker-font-size": "var(--font-size-md)",
  "--date-picker-header-arrow-filter": "opacity(1)",
  "--date-picker-header-color": "var(--color-on-surface-variant)",
  "--date-picker-header-padding": "0 0 16px",
  "--date-picker-main-color": "#1D1B20",
  "--date-picker-min-width": "290px",
  "--date-picker-title-background": "var(--color-surface-container-high)",
  "--date-picker-title-color": "#1D1B20",
  "--date-picker-title-date-font-size": "34px",
  "--date-picker-title-date-font-weight": "500",
  "--date-picker-title-date-height": "48px",
  "--date-picker-title-date-justify-content": "normal",
  "--date-picker-title-date-range-font-size": "20px",
  "--date-picker-title-height": "105px",
  "--date-picker-title-hint-color": "var(--color-on-surface-variant)",
  "--date-picker-title-hint-font-size": "var(--font-size-md)",
  "--date-picker-title-padding": "20px 20px 16px",
  "--date-picker-title-year-font-size": "var(--font-size-md)",
  "--date-picker-title-year-font-weight": "500",
  "--date-picker-title-year-margin-bottom": "8px",
  "--day-picker-content-item-button-font-size": "var(--font-size-sm)",
  "--day-picker-content-item-button-height": "32px",
  "--day-picker-content-item-button-width": "32px",
  "--day-picker-content-item-font-size": "var(--font-size-sm)",
  "--day-picker-content-item-padding": "2px 0",
  "--day-picker-content-item-width": "14.28%",
  "--day-picker-head-item-color": "#1D1B20",
  "--day-picker-head-item-font-weight": "600",
  "--day-picker-head-item-padding": "8px 0",
  "--dialog-actions-padding": "0 24px 24px",
  "--dialog-background": "var(--color-surface-container-high)",
  "--dialog-border-radius": "28px",
  "--dialog-button-margin-left": "8px",
  "--dialog-cancel-button-color": "var(--color-primary)",
  "--dialog-confirm-button-color": "var(--color-primary)",
  "--dialog-message-color": "var(--color-on-surface-variant)",
  "--dialog-message-font-size": "var(--font-size-md)",
  "--dialog-message-line-height": "24px",
  "--dialog-message-padding": "16px 24px 24px",
  "--dialog-title-color": "#1D1B20",
  "--dialog-title-font-size": "20px",
  "--dialog-title-padding": "24px 24px 0",
  "--dialog-width": "312px",
  "--divider-color": "var(--color-outline)",
  "--divider-inset": "72px",
  "--divider-text-color": "#888",
  "--divider-text-margin": "8px 0",
  "--divider-text-padding": "0 8px",
  "--fab-action-border-radius": "12px",
  "--fab-action-margin": "6px",
  "--fab-action-size": "40px",
  "--fab-actions-padding": "10px 0",
  "--fab-bottom": "16px",
  "--fab-left": "16px",
  "--fab-right": "16px",
  "--fab-top": "70px",
  "--fab-transition-standard-easing": "cubic-bezier(0.4, 0, 0.2, 1)",
  "--fab-trigger-active-icon-size": "22px",
  "--fab-trigger-border-radius": "16px",
  "--fab-trigger-inactive-icon-size": "26px",
  "--fab-trigger-size": "56px",
  "--field-decorator-blur-color": "#79747E",
  "--field-decorator-disabled-color": "var(--color-text-disabled)",
  "--field-decorator-error-color": "var(--color-danger)",
  "--field-decorator-filled-background-color": "var(--color-surface-container-high)",
  "--field-decorator-filled-border-radius": "4px",
  "--field-decorator-filled-normal-hint-center-margin-top": "16px",
  "--field-decorator-filled-normal-hint-margin-top": "16px",
  "--field-decorator-filled-normal-icon-margin-bottom": "16px",
  "--field-decorator-filled-normal-icon-margin-top": "16px",
  "--field-decorator-filled-normal-margin-bottom": "6px",
  "--field-decorator-filled-normal-margin-top": "26px",
  "--field-decorator-filled-normal-non-hint-margin-bottom": "16px",
  "--field-decorator-filled-normal-non-hint-margin-top": "16px",
  "--field-decorator-filled-normal-padding-left": "16px",
  "--field-decorator-filled-normal-padding-right": "16px",
  "--field-decorator-filled-normal-placeholder-hint-top": "4px",
  "--field-decorator-filled-normal-placeholder-space": "4px",
  "--field-decorator-filled-small-hint-center-margin-top": "10px",
  "--field-decorator-filled-small-hint-margin-top": "10px",
  "--field-decorator-filled-small-icon-margin-bottom": "10px",
  "--field-decorator-filled-small-icon-margin-top": "10px",
  "--field-decorator-filled-small-margin-bottom": "2px",
  "--field-decorator-filled-small-margin-top": "18px",
  "--field-decorator-filled-small-non-hint-margin-bottom": "10px",
  "--field-decorator-filled-small-non-hint-margin-top": "10px",
  "--field-decorator-filled-small-padding-left": "12px",
  "--field-decorator-filled-small-padding-right": "12px",
  "--field-decorator-filled-small-placeholder-hint-top": "2px",
  "--field-decorator-filled-small-placeholder-space": "2px",
  "--field-decorator-focus-color": "var(--color-primary)",
  "--field-decorator-icon-size": "20px",
  "--field-decorator-line-border-radius": "4px",
  "--field-decorator-line-focus-size": "2px",
  "--field-decorator-line-size": "1px",
  "--field-decorator-outlined-normal-icon-margin-bottom": "16px",
  "--field-decorator-outlined-normal-icon-margin-top": "16px",
  "--field-decorator-outlined-normal-margin-bottom": "16px",
  "--field-decorator-outlined-normal-margin-top": "16px",
  "--field-decorator-outlined-normal-padding-left": "16px",
  "--field-decorator-outlined-normal-padding-right": "16px",
  "--field-decorator-outlined-normal-placeholder-space": "4px",
  "--field-decorator-outlined-small-icon-margin-bottom": "8px",
  "--field-decorator-outlined-small-icon-margin-top": "8px",
  "--field-decorator-outlined-small-margin-bottom": "8px",
  "--field-decorator-outlined-small-margin-top": "8px",
  "--field-decorator-outlined-small-padding-left": "12px",
  "--field-decorator-outlined-small-padding-right": "12px",
  "--field-decorator-outlined-small-placeholder-space": "2px",
  "--field-decorator-placeholder-size": "16px",
  "--field-decorator-standard-normal-icon-margin-bottom": "4px",
  "--field-decorator-standard-normal-icon-margin-top": "22px",
  "--field-decorator-standard-normal-margin-bottom": "4px",
  "--field-decorator-standard-normal-margin-top": "22px",
  "--field-decorator-standard-normal-non-hint-margin-top": "4px",
  "--field-decorator-standard-small-icon-margin-bottom": "4px",
  "--field-decorator-standard-small-icon-margin-top": "18px",
  "--field-decorator-standard-small-margin-bottom": "4px",
  "--field-decorator-standard-small-margin-top": "18px",
  "--field-decorator-standard-small-non-hint-margin-top": "2px",
  "--field-decorator-text-color": "#1D1B20",
  "--floating-panel-background": "var(--color-surface-container-low)",
  "--floating-panel-border-radius": "0",
  "--floating-panel-border-top": "none",
  "--floating-panel-header-height": "36px",
  "--floating-panel-toolbar-background": "#79747E",
  "--floating-panel-toolbar-border-radius": "10px",
  "--floating-panel-toolbar-height": "4px",
  "--floating-panel-toolbar-width": "32px",
  "--floating-panel-transition-timing-function": "cubic-bezier(0.18, 0.89, 0.32, 1.28)",
  "--floating-panel-z-index": "999",
  "--font-size-lg": "16px",
  "--font-size-md": "14px",
  "--font-size-sm": "12px",
  "--font-size-xs": "10px",
  "--form-details-error-message-color": "var(--color-danger)",
  "--form-details-extra-message-color": "#888",
  "--form-details-font-size": "12px",
  "--form-details-margin-top": "6px",
  "--form-details-message-margin-right": "4px",
  "--hover-overlay-focusing-opacity": "var(--opacity-focus)",
  "--hover-overlay-opacity": "var(--opacity-hover)",
  "--hsl-body": "293, 100%, 98%",
  "--hsl-danger": "3, 71%, 41%",
  "--hsl-danger-container": "4, 71%, 92%",
  "--hsl-disabled": "0, 0%, 88%",
  "--hsl-info": "259, 11%, 40%",
  "--hsl-info-container": "263, 65%, 92%",
  "--hsl-inverse-surface": "270, 6%, 20%",
  "--hsl-on-danger": "0, 0%, 100%",
  "--hsl-on-danger-container": "3, 71%, 15%",
  "--hsl-on-info": "0, 0%, 100%",
  "--hsl-on-info-container": "253, 26%, 13%",
  "--hsl-on-primary": "0, 0%, 100%",
  "--hsl-on-primary-container": "261, 100%, 18%",
  "--hsl-on-success": "0, 0%, 100%",
  "--hsl-on-success-container": "79, 100%, 6%",
  "--hsl-on-surface-variant": "264, 7%, 29%",
  "--hsl-on-warning": "0, 0%, 100%",
  "--hsl-on-warning-container": "338, 48%, 13%",
  "--hsl-outline": "270, 11%, 79%",
  "--hsl-primary": "256, 34%, 48%",
  "--hsl-primary-container": "263, 100%, 93%",
  "--hsl-success": "77, 46%, 27%",
  "--hsl-success-container": "77, 68%, 77%",
  "--hsl-surface-container": "276, 38%, 95%",
  "--hsl-surface-container-high": "276, 25%, 92%",
  "--hsl-surface-container-highest": "280, 17%, 90%",
  "--hsl-surface-container-low": "278, 44%, 96%",
  "--hsl-text": "0, 0%, 0%",
  "--hsl-text-disabled": "0, 0%, 67%",
  "--hsl-warning": "340, 21%, 41%",
  "--hsl-warning-container": "342, 100%, 92%",
  "--icon-size": "20px",
  "--icon-size-lg": "22px",
  "--icon-size-md": "20px",
  "--icon-size-sm": "18px",
  "--icon-size-xs": "16px",
  "--image-preview-close-icon-color": "#fff",
  "--image-preview-close-icon-right": "14px",
  "--image-preview-close-icon-size": "22px",
  "--image-preview-close-icon-top": "14px",
  "--image-preview-extra-left": "14px",
  "--image-preview-extra-top": "14px",
  "--image-preview-swipe-indicators-padding": "16px 0",
  "--image-preview-swipe-indicators-text-color": "#ddd",
  "--image-preview-zoom-container-background": "#000",
  "--index-bar-list-bottom": "auto",
  "--index-bar-list-item-active-color": "var(--color-danger)",
  "--index-bar-list-item-color": "var(--color-primary)",
  "--index-bar-list-item-font-size": "var(--font-size-xs)",
  "--index-bar-list-item-height": "14px",
  "--index-bar-list-item-padding": "0 10px",
  "--index-bar-list-left": "auto",
  "--index-bar-list-right": "0",
  "--index-bar-list-top": "50%",
  "--index-bar-list-transform": "translate(0, -50%)",
  "--input-input-font-size": "16px",
  "--input-input-height": "24px",
  "--input-textarea-height": "auto",
  "--link-danger-color": "var(--color-danger)",
  "--link-default-color": "#000",
  "--link-disabled-color": "var(--color-text-disabled)",
  "--link-focus-opacity": "0.8",
  "--link-font-size": "var(--font-size-md)",
  "--link-info-color": "var(--color-info)",
  "--link-primary-color": "var(--color-primary)",
  "--link-success-color": "var(--color-success)",
  "--link-warning-color": "var(--color-warning)",
  "--list-error-color": "#888",
  "--list-error-font-size": "var(--font-size-md)",
  "--list-error-height": "50px",
  "--list-finished-color": "#888",
  "--list-finished-font-size": "var(--font-size-md)",
  "--list-finished-height": "50px",
  "--list-loading-color": "#888",
  "--list-loading-font-size": "var(--font-size-md)",
  "--list-loading-height": "50px",
  "--loading-bar-color": "var(--color-primary)",
  "--loading-bar-error-color": "var(--color-danger)",
  "--loading-bar-height": "3px",
  "--loading-color": "var(--color-primary)",
  "--loading-desc-color": "var(--color-primary)",
  "--loading-desc-margin": "8px 0 0",
  "--loading-opacity": "0.38",
  "--menu-background-color": "var(--color-surface-container)",
  "--menu-border-radius": "4px",
  "--menu-option-disabled-color": "var(--color-text-disabled)",
  "--menu-option-large-font-size": "var(--font-size-lg)",
  "--menu-option-large-height": "46px",
  "--menu-option-mini-font-size": "var(--font-size-xs)",
  "--menu-option-mini-height": "24px",
  "--menu-option-normal-font-size": "var(--font-size-md)",
  "--menu-option-normal-height": "38px",
  "--menu-option-padding": "0 12px",
  "--menu-option-selected-background": "var(--color-primary)",
  "--menu-option-small-font-size": "var(--font-size-sm)",
  "--menu-option-small-height": "30px",
  "--menu-option-text-color": "#1D1B20",
  "--menu-select-menu-background-color": "var(--color-surface-container)",
  "--menu-select-menu-border-radius": "4px",
  "--menu-select-menu-max-height": "278px",
  "--menu-select-menu-padding": "0",
  "--month-picker-item-button-max-width": "140px",
  "--month-picker-item-height": "56px",
  "--month-picker-item-width": "33%",
  "--month-picker-padding": "0 12px",
  "--opacity-disabled": "0.6",
  "--opacity-focus": "0.2",
  "--opacity-hover": "0.12",
  "--option-disabled-color": "var(--color-text-disabled)",
  "--option-font-size": "16px",
  "--option-height": "38px",
  "--option-padding": "0 12px",
  "--option-selected-background": "var(--field-decorator-focus-color)",
  "--option-text-color": "#1D1B20",
  "--overlay-background-color": "rgba(0, 0, 0, 0.6)",
  "--pagination-active-bg-color": "var(--color-primary)",
  "--pagination-active-color": "var(--color-on-primary)",
  "--pagination-bg-disabled-color": "var(--color-disabled)",
  "--pagination-disabled-color": "var(--color-text-disabled)",
  "--pagination-font-size": "var(--font-size-md)",
  "--pagination-hover-bg-color": "rgba(85, 85, 85, 0.15)",
  "--pagination-input-width": "32px",
  "--pagination-item-background": "#fff",
  "--pagination-item-border-radius": "4px",
  "--pagination-item-height": "32px",
  "--pagination-item-margin": "0 6px",
  "--pagination-item-simple-border-radius": "50%",
  "--pagination-item-width": "32px",
  "--pagination-quick-jumper-margin": "0 10px",
  "--pagination-size-line-height": "24px",
  "--pagination-size-padding": "0 4px",
  "--pagination-text-color": "#555",
  "--pagination-total-line-height": "24px",
  "--pagination-total-margin": "0 10px",
  "--paper-background": "var(--color-surface-container-low)",
  "--paper-border-radius": "12px",
  "--picker-background": "var(--color-body)",
  "--picker-cancel-button-text-color": "var(--color-primary)",
  "--picker-confirm-button-text-color": "var(--color-primary)",
  "--picker-mask-background-image": "linear-gradient(180deg, rgba(254, 247, 255, 0.9), rgba(254, 247, 255, 0.4)), linear-gradient(0deg, rgba(254, 247, 255, 0.9), rgba(254, 247, 255, 0.4))",
  "--picker-option-font-size": "var(--font-size-lg)",
  "--picker-option-text-color": "#555",
  "--picker-picked-border": "1px solid var(--color-outline)",
  "--picker-title-font-size": "var(--font-size-lg)",
  "--picker-title-text-color": "#555",
  "--picker-toolbar-height": "44px",
  "--picker-toolbar-padding": "0 4px",
  "--popup-content-background-color": "var(--color-surface-container-high)",
  "--popup-overlay-background-color": "rgba(0, 0, 0, 0.6)",
  "--progress-background": "var(--color-primary)",
  "--progress-danger-color": "var(--color-danger)",
  "--progress-default-color": "#f5f5f5",
  "--progress-font-size": "var(--font-size-sm)",
  "--progress-info-color": "var(--color-info)",
  "--progress-label-color": "#555",
  "--progress-linear-border-radius": "0px",
  "--progress-primary-color": "var(--color-primary)",
  "--progress-success-color": "var(--color-success)",
  "--progress-track-color": "#d8d8d8",
  "--progress-warning-color": "var(--color-warning)",
  "--pull-refresh-background": "var(--color-body)",
  "--pull-refresh-color": "var(--color-primary)",
  "--pull-refresh-icon-size": "25px",
  "--pull-refresh-size": "40px",
  "--pull-refresh-success-color": "var(--color-success)",
  "--radio-action-padding": "6px",
  "--radio-checked-color": "var(--color-primary)",
  "--radio-disabled-color": "var(--color-text-disabled)",
  "--radio-error-color": "var(--color-danger)",
  "--radio-icon-size": "24px",
  "--radio-text-color": "var(--color-on-surface-variant)",
  "--radio-unchecked-color": "var(--color-on-surface-variant)",
  "--rate-action-padding": "4px",
  "--rate-color": "var(--color-on-surface-variant)",
  "--rate-disabled-color": "var(--color-text-disabled)",
  "--rate-error-color": "var(--color-danger)",
  "--rate-primary-color": "var(--color-primary)",
  "--rate-size": "24px",
  "--result-background": "var(--color-body)",
  "--result-border-radius": "12px",
  "--result-description-color": "var(--color-on-surface-variant)",
  "--result-description-font-size": "14px",
  "--result-description-line-height": "1.6",
  "--result-description-margin": "10px 0 0 0",
  "--result-empty-border-color": "rgba(158, 158, 158, 0.3)",
  "--result-empty-color": "#9e9e9e",
  "--result-error-border-color": "rgba(179, 38, 30, 0.3)",
  "--result-error-color": "var(--color-danger)",
  "--result-image-size": "80px",
  "--result-info-border-color": "rgba(98, 91, 113, 0.3)",
  "--result-info-color": "var(--color-info)",
  "--result-padding": "24px",
  "--result-question-border-color": "rgba(96, 125, 139, 0.3)",
  "--result-question-color": "#607d8b",
  "--result-success-border-color": "rgba(83, 101, 37, 0.3)",
  "--result-success-color": "var(--color-success)",
  "--result-title-color": "#1D1B20",
  "--result-title-font-size": "32px",
  "--result-title-font-weight": "500",
  "--result-title-margin": "15px 0 0 0",
  "--result-warning-border-color": "rgba(125, 82, 96, 0.3)",
  "--result-warning-color": "var(--color-warning)",
  "--ripple-color": "currentColor",
  "--ripple-cubic-bezier": "cubic-bezier(0.68, 0.01, 0.62, 0.6)",
  "--select-arrow-size": "20px",
  "--select-chip-background-color": "rgb(218, 212, 219)",
  "--select-chip-margin": "5px 5px 0 0",
  "--select-chips-margin": "-5px 0 0 0",
  "--select-chips-padding": "2px 0",
  "--select-label-font-size": "16px",
  "--select-scroller-background": "var(--color-surface-container)",
  "--select-scroller-border-radius": "4px",
  "--select-scroller-max-height": "278px",
  "--select-scroller-padding": "6px 0",
  "--select-standard-menu-margin": "calc(var(--field-decorator-placeholder-size) * 0.75 + 12px) 0 0 0",
  "--shadow-key-ambient-opacity": "rgba(0, 0, 0, 0.12)",
  "--shadow-key-penumbra-opacity": "rgba(0, 0, 0, 0.14)",
  "--shadow-key-umbra-opacity": "rgba(0, 0, 0, 0.2)",
  "--signature-background-color": "var(--color-surface-container-low)",
  "--signature-border-radius": "12px",
  "--signature-height": "200px",
  "--signature-stroke-color": "#1D1B20",
  "--skeleton-animation-background": "linear-gradient(90deg, hsla(0, 0%, 100%, 0), hsla(0, 0%, 100%, 0.3), hsla(0, 0%, 100%, 0))",
  "--skeleton-avatar-background-color": "rgba(0, 0, 0, 0.12)",
  "--skeleton-avatar-border-radius": "50%",
  "--skeleton-avatar-margin-right": "16px",
  "--skeleton-avatar-size": "34px",
  "--skeleton-card-background-color": "rgba(0, 0, 0, 0.12)",
  "--skeleton-card-border-radius": "4px",
  "--skeleton-card-height": "160px",
  "--skeleton-card-margin-bottom": "16px",
  "--skeleton-content-padding": "16px",
  "--skeleton-row-border-radius": "10px",
  "--skeleton-row-height": "12px",
  "--skeleton-row-margin-top": "10px",
  "--skeleton-title-background-color": "rgba(0, 0, 0, 0.12)",
  "--skeleton-title-border-radius": "10px",
  "--skeleton-title-width": "50%",
  "--slider-disabled-opacity": "var(--opacity-disabled)",
  "--slider-error-color": "var(--color-danger)",
  "--slider-thumb-block-background": "var(--color-primary)",
  "--slider-thumb-label-background": "var(--color-primary)",
  "--slider-thumb-label-font-size": "var(--font-size-sm)",
  "--slider-thumb-label-text-color": "var(--color-on-primary)",
  "--slider-thumb-ripple-background": "var(--color-primary)",
  "--slider-thumb-size": "16px",
  "--slider-track-background": "var(--color-surface-container-highest)",
  "--slider-track-border-radius": "4px",
  "--slider-track-fill-background": "var(--color-primary)",
  "--slider-track-fill-border-radius": "4px",
  "--slider-track-height": "4px",
  "--snackbar-action-margin": "0 8px",
  "--snackbar-background": "var(--color-inverse-surface)",
  "--snackbar-border-color": "currentColor",
  "--snackbar-border-radius": "4px",
  "--snackbar-color": "#F5EFF7",
  "--snackbar-content-padding": "14px 16px",
  "--snackbar-error-background": "var(--color-danger)",
  "--snackbar-font-size": "var(--font-size-md)",
  "--snackbar-icon-margin": "0 8px",
  "--snackbar-info-background": "var(--color-info)",
  "--snackbar-margin": "6px 24px",
  "--snackbar-success-background": "var(--color-success)",
  "--snackbar-vertical-action-margin": "0 8px 8px 0",
  "--snackbar-warning-background": "var(--color-warning)",
  "--snackbar-width": "256px",
  "--space-size-large-x": "20px",
  "--space-size-large-y": "12px",
  "--space-size-mini-x": "4px",
  "--space-size-mini-y": "4px",
  "--space-size-normal-x": "12px",
  "--space-size-normal-y": "8px",
  "--space-size-small-x": "6px",
  "--space-size-small-y": "6px",
  "--step-content-active-color": "#000",
  "--step-content-color": "rgba(0, 0, 0, 0.38)",
  "--step-content-font-size": "var(--font-size-md)",
  "--step-line-background": "#000",
  "--step-line-gap": "8px",
  "--step-tag-active-color": "var(--color-primary)",
  "--step-tag-background": "#9e9e9e",
  "--step-tag-color": "var(--color-on-primary)",
  "--step-tag-font-size": "var(--font-size-md)",
  "--step-tag-icon-size": "var(--font-size-lg)",
  "--step-tag-margin": "4px 0",
  "--step-tag-size": "20px",
  "--step-vertical-min-height": "50px",
  "--step-vertical-tag-margin": "0 4px",
  "--swipe-indicator-color": "#fff",
  "--swipe-indicator-offset": "4px",
  "--swipe-indicators-offset": "10px",
  "--swipe-navigation-button-border-radius": "50%",
  "--swipe-navigation-button-height": "36px",
  "--swipe-navigation-button-width": "36px",
  "--swipe-navigation-icon-size": "20px",
  "--swipe-navigation-next-bottom": "8px",
  "--swipe-navigation-next-right": "8px",
  "--swipe-navigation-prev-left": "8px",
  "--swipe-navigation-prev-top": "8px",
  "--swipe-navigation-z-index": "9",
  "--switch-disabled-opacity": "var(--opacity-disabled)",
  "--switch-handle-active-background": "var(--color-primary)",
  "--switch-handle-active-color": "var(--color-on-primary)",
  "--switch-handle-background": "var(--color-surface-container-low)",
  "--switch-handle-color": "var(--color-primary)",
  "--switch-handle-error-background": "var(--color-danger)",
  "--switch-handle-height": "20px",
  "--switch-handle-width": "20px",
  "--switch-height": "24px",
  "--switch-loading-size": "16px",
  "--switch-ripple-active-left": "10px",
  "--switch-ripple-color": "var(--color-primary)",
  "--switch-ripple-left": "-10px",
  "--switch-ripple-size": "40px",
  "--switch-track-active-background": "var(--color-primary)",
  "--switch-track-background": "var(--color-surface-container-low)",
  "--switch-track-border-radius": "calc(20px * 2 / 3)",
  "--switch-track-error-background": "var(--color-danger)",
  "--switch-track-height": "14.4px",
  "--switch-track-width": "38px",
  "--switch-variant-handle-active-background": "var(--color-on-primary)",
  "--switch-variant-handle-active-color": "var(--color-primary)",
  "--switch-variant-handle-background": "#79747E",
  "--switch-variant-handle-color": "var(--color-on-primary)",
  "--switch-variant-handle-height": "24px",
  "--switch-variant-handle-width": "24px",
  "--switch-variant-height": "32px",
  "--switch-variant-ripple-active-left": "16px",
  "--switch-variant-ripple-left": "-4px",
  "--switch-variant-track-background": "var(--color-surface-container-highest)",
  "--switch-variant-track-border-color": "#79747E",
  "--switch-variant-width": "52px",
  "--switch-width": "40px",
  "--tab-active-color": "var(--color-primary)",
  "--tab-active-font-size": "var(--font-size-md)",
  "--tab-active-font-weight": "400",
  "--tab-disabled-color": "var(--color-text-disabled)",
  "--tab-font-size": "var(--font-size-md)",
  "--tab-font-weight": "400",
  "--tab-inactive-color": "var(--color-on-surface-variant)",
  "--tab-padding": "12px",
  "--table-background": "var(--color-surface-container-low)",
  "--table-border-radius": "2px",
  "--table-footer-border-top": "thin solid var(--color-outline)",
  "--table-row-height": "46px",
  "--table-row-padding": "0 16px",
  "--table-tbody-td-font-size": "16px",
  "--table-tbody-td-text-align": "left",
  "--table-tbody-td-text-color": "#555",
  "--table-tbody-tr-border-bottom": "thin solid var(--color-outline)",
  "--table-tbody-tr-hover-background": "var(--color-surface-container-low)",
  "--table-thead-border-bottom": "thin solid var(--color-outline)",
  "--table-thead-th-font-size": "14px",
  "--table-thead-th-text-align": "left",
  "--table-thead-th-text-color": "rgba(0, 0, 0, 0.6)",
  "--table-thead-tr-border-bottom": "thin solid var(--color-outline)",
  "--tabs-background": "var(--color-body)",
  "--tabs-indicator-background": "var(--color-primary)",
  "--tabs-indicator-border-radius": "0",
  "--tabs-indicator-inner-size": "100%",
  "--tabs-indicator-size": "2px",
  "--tabs-item-horizontal-height": "44px",
  "--tabs-item-vertical-height": "66px",
  "--tabs-padding": "12px",
  "--tabs-radius": "2px",
  "--time-picker-actions-padding": "20px",
  "--time-picker-body-background": "var(--color-surface-container-high)",
  "--time-picker-body-height": "288px",
  "--time-picker-border-radius": "20px",
  "--time-picker-clock-bottom": "27px",
  "--time-picker-clock-container-background": "var(--color-surface-container-highest)",
  "--time-picker-clock-container-height": "256px",
  "--time-picker-clock-container-width": "256px",
  "--time-picker-clock-hand-after-height": "4px",
  "--time-picker-clock-hand-after-width": "4px",
  "--time-picker-clock-hand-background": "var(--color-primary)",
  "--time-picker-clock-hand-before-border-width": "2px",
  "--time-picker-clock-hand-before-height": "10px",
  "--time-picker-clock-hand-before-width": "10px",
  "--time-picker-clock-hand-border-color": "var(--color-primary)",
  "--time-picker-clock-hand-bottom": "50%",
  "--time-picker-clock-hand-height": "calc(50% - 4px)",
  "--time-picker-clock-hand-left": "calc(50% - 1px)",
  "--time-picker-clock-hand-width": "2px",
  "--time-picker-clock-item-active-background": "var(--color-primary)",
  "--time-picker-clock-item-active-color": "var(--color-on-primary)",
  "--time-picker-clock-item-disable-background": "#bdbdbd",
  "--time-picker-clock-item-disable-color": "rgba(0, 0, 0, 0.26)",
  "--time-picker-clock-item-height": "32px",
  "--time-picker-clock-item-text-color": "#1D1B20",
  "--time-picker-clock-item-width": "32px",
  "--time-picker-clock-left": "27px",
  "--time-picker-clock-right": "27px",
  "--time-picker-clock-top": "27px",
  "--time-picker-font-size": "var(--font-size-md)",
  "--time-picker-inner-bottom": "36px",
  "--time-picker-inner-left": "36px",
  "--time-picker-inner-right": "36px",
  "--time-picker-inner-top": "36px",
  "--time-picker-min-width": "290px",
  "--time-picker-title-ampm-border": "thin solid #79747e",
  "--time-picker-title-ampm-border-radius": "8px",
  "--time-picker-title-ampm-button-active-background": "var(--color-warning-container)",
  "--time-picker-title-ampm-button-padding": "8px",
  "--time-picker-title-ampm-margin-left": "10px",
  "--time-picker-title-background": "var(--color-surface-container-high)",
  "--time-picker-title-color": "#1D1B20",
  "--time-picker-title-height": "105px",
  "--time-picker-title-hint-color": "var(--color-on-surface-variant)",
  "--time-picker-title-hint-font-size": "14px",
  "--time-picker-title-inactive-opacity": "1",
  "--time-picker-title-margin-bottom": "20px",
  "--time-picker-title-padding": "20px 20px 16px",
  "--time-picker-title-time-active-background": "var(--color-primary-container)",
  "--time-picker-title-time-background": "var(--color-surface-container-highest)",
  "--time-picker-title-time-border-radius": "8px",
  "--time-picker-title-time-container-justify-content": "flex-end",
  "--time-picker-title-time-font-size": "40px",
  "--time-picker-title-time-margin": "0 5px",
  "--time-picker-title-time-padding": "8px 12px",
  "--tooltip-border-radius": "4px",
  "--tooltip-danger-color": "var(--color-danger)",
  "--tooltip-danger-text-color": "var(--color-on-danger)",
  "--tooltip-default-color": "var(--color-inverse-surface)",
  "--tooltip-default-text-color": "#fff",
  "--tooltip-font-size": "14px",
  "--tooltip-info-color": "var(--color-info)",
  "--tooltip-info-text-color": "var(--color-on-info)",
  "--tooltip-offset": "10px",
  "--tooltip-opacity": "1",
  "--tooltip-padding": "8px 16px",
  "--tooltip-primary-color": "var(--color-primary)",
  "--tooltip-primary-text-color": "var(--color-on-primary)",
  "--tooltip-success-color": "var(--color-success)",
  "--tooltip-success-text-color": "var(--color-on-success)",
  "--tooltip-warning-color": "var(--color-warning)",
  "--tooltip-warning-text-color": "var(--color-on-warning)",
  "--uploader-action-background": "var(--color-surface-container-low)",
  "--uploader-action-icon-color": "var(--color-on-surface-variant)",
  "--uploader-action-icon-size": "24px",
  "--uploader-action-margin": "0 10px 10px 0",
  "--uploader-disabled-color": "var(--color-disabled)",
  "--uploader-disabled-text-color": "var(--color-text-disabled)",
  "--uploader-file-border-radius": "8px",
  "--uploader-file-close-background": "rgba(0, 0, 0, 0.3)",
  "--uploader-file-close-icon-color": "#fff",
  "--uploader-file-close-icon-font-size": "14px",
  "--uploader-file-close-size": "24px",
  "--uploader-file-cover-background": "var(--color-surface-container-low)",
  "--uploader-file-cover-fit": "cover",
  "--uploader-file-indicator-error-color": "var(--color-danger)",
  "--uploader-file-indicator-height": "4px",
  "--uploader-file-indicator-normal-color": "var(--color-disabled)",
  "--uploader-file-indicator-success-color": "var(--color-success)",
  "--uploader-file-margin": "0 10px 10px 0",
  "--uploader-file-name-background": "var(--color-surface-container-low)",
  "--uploader-file-name-color": "var(--color-on-surface-variant)",
  "--uploader-file-name-font-size": "12px",
  "--uploader-file-name-padding": "10px",
  "--uploader-file-progress-color": "var(--color-primary)",
  "--uploader-file-size": "80px",
  "--uploader-file-text-align": "center",
  "--uploader-loading-background": "linear-gradient(90deg, hsla(0, 0%, 100%, 0), hsla(0, 0%, 100%, 0.3), hsla(0, 0%, 100%, 0))",
  "--uploader-preview-video-height": "100vw",
  "--uploader-preview-video-width": "100vw",
  "--watermark-content-color": "#808080",
  "--year-picker-item-button-max-width": "140px",
  "--year-picker-item-height": "56px",
  "--year-picker-item-width": "33%",
  "--year-picker-padding": "0 12px",
} satisfies StyleVars

export default md3Light
