packages:
  - 'apps/*'
  - 'packages/*'
  # Exclude vscode from workspace
  - '!vscode'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - electron
  - esbuild
  - lmdb
  - msgpackr-extract

onlyBuiltDependencies:
  - electron-winstaller
