/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/hello-world.vue')['default']
    KeypressVisualizer: typeof import('./src/components/keypress-visualizer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UCommandPalette: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue')['default']
    UModal: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
  }
}

// For TSX support
declare global {
  const HelloWorld: typeof import('./src/components/hello-world.vue')['default']
  const KeypressVisualizer: typeof import('./src/components/keypress-visualizer.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UCommandPalette: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue')['default']
  const UModal: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
}