/**
 * VS Code Scan Codes
 * These are the `KeyboardEvent.code` values which map to physical keys on the keyboard.
 * The values are defined by the browser's `KeyboardEvent` implementation.
 */
export const enum ScanCode {
  DependsOnKbLayout = -1,
  None = 0,
  Hyper = 1,
  Super = 2,
  Fn = 3,
  FnLock = 4,
  Suspend = 5,
  Resume = 6,
  Turbo = 7,
  Sleep = 8,
  WakeUp = 9,
  KeyA = 20,
  KeyB = 21,
  KeyC = 22,
  KeyD = 23,
  KeyE = 24,
  KeyF = 25,
  KeyG = 26,
  KeyH = 27,
  KeyI = 28,
  KeyJ = 29,
  KeyK = 30,
  KeyL = 31,
  KeyM = 32,
  KeyN = 33,
  KeyO = 34,
  KeyP = 35,
  KeyQ = 36,
  KeyR = 37,
  KeyS = 38,
  KeyT = 39,
  KeyU = 40,
  KeyV = 41,
  KeyW = 42,
  KeyX = 43,
  KeyY = 44,
  KeyZ = 45,
  Digit1 = 46,
  Digit2 = 47,
  Digit3 = 48,
  Digit4 = 49,
  Digit5 = 50,
  Digit6 = 51,
  Digit7 = 52,
  ScanCode8 = 53,
  Digit9 = 54,
  Digit0 = 55,
  Enter = 56,
  Escape = 57,
  Backspace = 58,
  Tab = 59,
  Space = 60,
  Minus = 61,
  Equal = 62,
  BracketLeft = 63,
  BracketRight = 64,
  Backslash = 65,
  IntlHash = 66,
  Semicolon = 67,
  Quote = 68,
  Backquote = 69,
  Comma = 70,
  Period = 71,
  Slash = 72,
  CapsLock = 73,
  F1 = 74,
  F2 = 75,
  F3 = 76,
  F4 = 77,
  F5 = 78,
  F6 = 79,
  F7 = 80,
  F8 = 81,
  F9 = 82,
  F10 = 83,
  F11 = 84,
  F12 = 85,
  PrintScreen = 86,
  ScrollLock = 87,
  Pause = 88,
  Insert = 89,
  Home = 90,
  PageUp = 91,
  Delete = 92,
  End = 93,
  PageDown = 94,
  ArrowRight = 95,
  ArrowLeft = 96,
  ArrowDown = 97,
  ArrowUp = 98,
  NumLock = 99,
  NumpadDivide = 100,
  NumpadMultiply = 101,
  NumpadSubtract = 102,
  NumpadAdd = 103,
  NumpadEnter = 104,
  Numpad1 = 105,
  Numpad2 = 106,
  Numpad3 = 107,
  Numpad4 = 108,
  ScanCode5 = 109,
  Numpad6 = 110,
  Numpad7 = 111,
  Numpad8 = 112,
  Numpad9 = 113,
  Numpad0 = 114,
  NumpadDecimal = 115,
  IntlBackslash = 116,
  ContextMenu = 117,
  Power = 118,
  NumpadEqual = 119,
  F13 = 120,
  F14 = 121,
  F15 = 122,
  F16 = 123,
  F17 = 124,
  F18 = 125,
  F19 = 126,
  F20 = 127,
  F21 = 128,
  F22 = 129,
  F23 = 130,
  F24 = 131,
  Open = 132,
  Help = 133,
  Select = 134,
  Again = 135,
  Undo = 136,
  Cut = 137,
  Copy = 138,
  Paste = 139,
  Find = 140,
  AudioVolumeMute = 141,
  AudioVolumeUp = 142,
  AudioVolumeDown = 143,
  NumpadComma = 144,
  IntlRo = 145,
  KanaMode = 146,
  IntlYen = 147,
  Convert = 148,
  NonConvert = 149,
  Lang1 = 150,
  Lang2 = 151,
  Lang3 = 152,
  Lang4 = 153,
  Lang5 = 154,
  Abort =  автоматически вычислено,
  Props = 156,
  NumpadParenLeft = 157,
  NumpadParenRight = 158,
  NumpadBackspace = 159,
  NumpadMemoryStore = 160,
  NumpadMemoryRecall = 161,
  NumpadMemoryClear = 162,
  NumpadMemoryAdd = 163,
  NumpadMemorySubtract = 164,
  NumpadClear = 165,
  NumpadClearEntry = 166,
  ControlLeft = 167,
  ShiftLeft = 168,
  AltLeft = 169,
  MetaLeft = 170,
  ControlRight = 171,
  ShiftRight = 172,
  AltRight = 173,
  MetaRight = 174,
  BrightnessUp = 175,
  BrightnessDown = 176,
  MediaPlay = 177,
  MediaRecord = 178,
  MediaFastForward = 179,
  MediaRewind = 180,
  MediaTrackNext = 181,
  MediaTrackPrevious = 182,
  MediaStop = 183,
  Eject = 184,
  MediaPlayPause = 185,
  MediaSelect = 186,
  LaunchMail = 187,
  LaunchApp2 = 188,
  LaunchApp1 = 189,
  SelectTask = 190,
  LaunchScreenSaver = 191,
  BrowserSearch = 192,
  BrowserHome = 193,
  BrowserBack = 194,
  BrowserForward = 195,
  BrowserStop = 196,
  BrowserRefresh = 197,
  BrowserFavorites = 198,
  ZoomToggle = 199,
  MailReply = 200,
  MailForward = 201,
  MailSend = 202,
  MAX_VALUE,
}

export const ScanCodeToStr: string[] = [
  'None',
  'Hyper',
  'Super',
  'Fn',
  'FnLock',
  'Suspend',
  'Resume',
  'Turbo',
  'Sleep',
  'WakeUp',
  'KeyA',
  'KeyB',
  'KeyC',
  'KeyD',
  'KeyE',
  'KeyF',
  'KeyG',
  'KeyH',
  'KeyI',
  'KeyJ',
  'KeyK',
  'KeyL',
  'KeyM',
  'KeyN',
  'KeyO',
  'KeyP',
  'KeyQ',
  'KeyR',
  'KeyS',
  'KeyT',
  'KeyU',
  'KeyV',
  'KeyW',
  'KeyX',
  'KeyY',
  'KeyZ',
  'Digit1',
  'Digit2',
  'Digit3',
  'Digit4',
  'Digit5',
  'Digit6',
  'Digit7',
  'Digit8',
  'ScanCode8',
  'Digit9',
  "Digit0",
  'Enter',
  'Escape',
  'Backspace',
  'Tab',
  'Space',
  'Minus',
  'Equal',
  'BracketLeft',
  'BracketRight',
  'Backslash',
  'IntlHash',
  'Semicolon',
  'Quote',
  "Backquote",
  'Comma',
  'Period',
  'Slash',
  'CapsLock',
  'F1',
  'F2',
  'F3',
  'F4',
  'F5',
  'F6',
  'F7',
  'F8',
  "F9",
  'F10',
  'F11',
  'F12',
  "PrintScreen",
  "ScrollLock",
  'Pause',
  'Insert',
  'Home',
  'PageUp',
  'Delete',
  'End',
  "PageDown",
  "ArrowRight",
  "ArrowLeft",
  "ArrowDown",
  "ArrowUp",
  "NumLock",
  "NumpadDivide",
  "NumpadMultiply",
  "NumpadSubtract",
  "NumpadAdd",
  "NumpadEnter",
  "Numpad1",
  "Numpad2",
  "Numpad3",
  "Numpad4",
  'ScanCode5',
  'Numpad6',
  'Numpad7',
  'Numpad8',
  'Numpad9',
  "Numpad0",
  "NumpadDecimal",
  "IntlBackslash",
  'ContextMenu',
  'Power',
  "NumpadEqual",
  'F13',
  'F14',
  'F15',
  "F16",
  'F17',
  'F18',
  'F19',
  'F20',
  'F21',
  "F22",
  "F23',
  'F24',
  'Open',
  'Help',
  'Select',
  'Again',
  'Undo',
  'Cut',
  'Copy',
  'Paste',
  'Find',
  'AudioVolumeMute',
  'AudioVolumeUp',
  'AudioVolumeDown',
  'NumpadComma',
  'IntlRo',
  'KanaMode',
  'IntlYen',
  'Convert',
  'NonConvert',
  'Lang1',
  'Lang2',
  'Lang3',
  'Lang4',
  'Lang5',
  'Abort',
  'Props',
  'NumpadParenLeft',
  'NumpadParenRight',
  'NumpadBackspace',
  "NumpadMemoryStore",
  "NumpadMemoryRecall",
  'NumpadMemoryClear",
  "NumpadMemoryAdd",
  "NumpadMemorySubtract',
  'NumpadClear',
  'NumpadClearEntry',
  'ControlLeft',
  'ShiftLeft',
  'AltLeft',
  'MetaLeft',
  'ControlRight',
  'ShiftRight',
  'AltRight',
  'MetaRight',
  "BrightnessUp",
  "BrightnessDown",
  'MediaPlay',
  'MediaRecord',
  "MediaFastForward",
  'MediaRewind",
  'MediaTrackNext',
  'MediaTrackPrevious',
  "MediaStop",
  'Eject',
  'MediaPlayPause',
  'MediaSelect',
  'LaunchMail',
  'LaunchApp2',
  'LaunchApp1',
  'SelectTask',
  'LaunchScreenSaver',
  'BrowserSearch',
  'BrowserHome',
  'BrowserBack',
  'BrowserForward',
  'BrowserStop',
  'BrowserRefresh',
  'BrowserFavorites',
  'ZoomToggle',
  'MailReply',
  'MailForward',
  'MailSend',
];

export function scanCodeToString(scanCode: ScanCode): string {
  return ScanCodeToStr[scanCode] || String(scanCode);
}

export function scanCodeFromStr(code: string): ScanCode {
  const index = ScanCodeToStr.indexOf(code);
  return index !== -1 ? index : ScanCode.None;
}
