/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * VS Code Scan Codes
 * These are the `KeyboardEvent.code` values which map to physical keys on the keyboard.
 * The values are defined by the browser's `KeyboardEvent` implementation.
 */
export const enum ScanCode {
  DependsOnKbLayout = -1,
  None = 0,
  Hyper = 1,
  Super = 2,
  Fn = 3,
  FnLock = 4,
  Suspend = 5,
  Resume = 6,
  Turbo = 7,
  Sleep = 8,
  WakeUp = 9,
  KeyA = 10,
  KeyB = 11,
  KeyC = 12,
  KeyD = 13,
  KeyE = 14,
  KeyF = 15,
  KeyG = 16,
  KeyH = 17,
  KeyI = 18,
  KeyJ = 19,
  KeyK = 20,
  KeyL = 21,
  KeyM = 22,
  KeyN = 23,
  KeyO = 24,
  KeyP = 25,
  KeyQ = 26,
  KeyR = 27,
  KeyS = 28,
  KeyT = 29,
  KeyU = 30,
  KeyV = 31,
  KeyW = 32,
  KeyX = 33,
  KeyY = 34,
  KeyZ = 35,
  Digit1 = 36,
  Digit2 = 37,
  Digit3 = 38,
  Digit4 = 39,
  Digit5 = 40,
  Digit6 = 41,
  Digit7 = 42,
  Digit8 = 43,
  Digit9 = 44,
  Digit0 = 45,
  Enter = 46,
  Escape = 47,
  Backspace = 48,
  Tab = 49,
  Space = 50,
  Minus = 51,
  Equal = 52,
  BracketLeft = 53,
  BracketRight = 54,
  Backslash = 55,
  IntlHash = 56,
  Semicolon = 57,
  Quote = 58,
  Backquote = 59,
  Comma = 60,
  Period = 61,
  Slash = 62,
  CapsLock = 63,
  F1 = 64,
  F2 = 65,
  F3 = 66,
  F4 = 67,
  F5 = 68,
  F6 = 69,
  F7 = 70,
  F8 = 71,
  F9 = 72,
  F10 = 73,
  F11 = 74,
  F12 = 75,
  PrintScreen = 76,
  ScrollLock = 77,
  Pause = 78,
  Insert = 79,
  Home = 80,
  PageUp = 81,
  Delete = 82,
  End = 83,
  PageDown = 84,
  ArrowRight = 85,
  ArrowLeft = 86,
  ArrowDown = 87,
  ArrowUp = 88,
  NumLock = 89,
  NumpadDivide = 90,
  NumpadMultiply = 91,
  NumpadSubtract = 92,
  NumpadAdd = 93,
  NumpadEnter = 94,
  Numpad1 = 95,
  Numpad2 = 96,
  Numpad3 = 97,
  Numpad4 = 98,
  Numpad5 = 99,
  Numpad6 = 100,
  Numpad7 = 101,
  Numpad8 = 102,
  Numpad9 = 103,
  Numpad0 = 104,
  NumpadDecimal = 105,
  IntlBackslash = 106,
  ContextMenu = 107,
  Power = 108,
  NumpadEqual = 109,
  F13 = 110,
  F14 = 111,
  F15 = 112,
  F16 = 113,
  F17 = 114,
  F18 = 115,
  F19 = 116,
  F20 = 117,
  F21 = 118,
  F22 = 119,
  F23 = 120,
  F24 = 121,
  Open = 122,
  Help = 123,
  Select = 124,
  Again = 125,
  Undo = 126,
  Cut = 127,
  Copy = 128,
  Paste = 129,
  Find = 130,
  AudioVolumeMute = 131,
  AudioVolumeUp = 132,
  AudioVolumeDown = 133,
  NumpadComma = 134,
  IntlRo = 135,
  KanaMode = 136,
  IntlYen = 137,
  Convert = 138,
  NonConvert = 139,
  Lang1 = 140,
  Lang2 = 141,
  Lang3 = 142,
  Lang4 = 143,
  Lang5 = 144,
  Abort = 145,
  Props = 146,
  NumpadParenLeft = 147,
  NumpadParenRight = 148,
  NumpadBackspace = 149,
  NumpadMemoryStore = 150,
  NumpadMemoryRecall = 151,
  NumpadMemoryClear = 152,
  NumpadMemoryAdd = 153,
  NumpadMemorySubtract = 154,
  NumpadClear = 155,
  NumpadClearEntry = 156,
  ControlLeft = 157,
  ShiftLeft = 158,
  AltLeft = 159,
  MetaLeft = 160,
  ControlRight = 161,
  ShiftRight = 162,
  AltRight = 163,
  MetaRight = 164,
  BrightnessUp = 165,
  BrightnessDown = 166,
  MediaPlay = 167,
  MediaRecord = 168,
  MediaFastForward = 169,
  MediaRewind = 170,
  MediaTrackNext = 171,
  MediaTrackPrevious = 172,
  MediaStop = 173,
  Eject = 174,
  MediaPlayPause = 175,
  MediaSelect = 176,
  LaunchMail = 177,
  LaunchApp2 = 178,
  LaunchApp1 = 179,
  SelectTask = 180,
  LaunchScreenSaver = 181,
  BrowserSearch = 182,
  BrowserHome = 183,
  BrowserBack = 184,
  BrowserForward = 185,
  BrowserStop = 186,
  BrowserRefresh = 187,
  BrowserFavorites = 188,
  ZoomToggle = 189,
  MailReply = 190,
  MailForward = 191,
  MailSend = 192,
  MAX_VALUE = 193,
}

export const ScanCodeToStr: string[] = [
  'None',
  'Hyper',
  'Super',
  'Fn',
  'FnLock',
  'Suspend',
  'Resume',
  'Turbo',
  'Sleep',
  'WakeUp',
  'KeyA',
  'KeyB',
  'KeyC',
  'KeyD',
  'KeyE',
  'KeyF',
  'KeyG',
  'KeyH',
  'KeyI',
  'KeyJ',
  'KeyK',
  'KeyL',
  'KeyM',
  'KeyN',
  'KeyO',
  'KeyP',
  'KeyQ',
  'KeyR',
  'KeyS',
  'KeyT',
  'KeyU',
  'KeyV',
  'KeyW',
  'KeyX',
  'KeyY',
  'KeyZ',
  'Digit1',
  'Digit2',
  'Digit3',
  'Digit4',
  'Digit5',
  'Digit6',
  'Digit7',
  'Digit8',
  'Digit9',
  'Digit0',
  'Enter',
  'Escape',
  'Backspace',
  'Tab',
  'Space',
  'Minus',
  'Equal',
  'BracketLeft',
  'BracketRight',
  'Backslash',
  'IntlHash',
  'Semicolon',
  'Quote',
  'Backquote',
  'Comma',
  'Period',
  'Slash',
  'CapsLock',
  'F1',
  'F2',
  'F3',
  'F4',
  'F5',
  'F6',
  'F7',
  'F8',
  'F9',
  'F10',
  'F11',
  'F12',
  'PrintScreen',
  'ScrollLock',
  'Pause',
  'Insert',
  'Home',
  'PageUp',
  'Delete',
  'End',
  'PageDown',
  'ArrowRight',
  'ArrowLeft',
  'ArrowDown',
  'ArrowUp',
  'NumLock',
  'NumpadDivide',
  'NumpadMultiply',
  'NumpadSubtract',
  'NumpadAdd',
  'NumpadEnter',
  'Numpad1',
  'Numpad2',
  'Numpad3',
  'Numpad4',
  'Numpad5',
  'Numpad6',
  'Numpad7',
  'Numpad8',
  'Numpad9',
  'Numpad0',
  'NumpadDecimal',
  'IntlBackslash',
  'ContextMenu',
  'Power',
  'NumpadEqual',
  'F13',
  'F14',
  'F15',
  'F16',
  'F17',
  'F18',
  'F19',
  'F20',
  'F21',
  'F22',
  'F23',
  'F24',
  'Open',
  'Help',
  'Select',
  'Again',
  'Undo',
  'Cut',
  'Copy',
  'Paste',
  'Find',
  'AudioVolumeMute',
  'AudioVolumeUp',
  'AudioVolumeDown',
  'NumpadComma',
  'IntlRo',
  'KanaMode',
  'IntlYen',
  'Convert',
  'NonConvert',
  'Lang1',
  'Lang2',
  'Lang3',
  'Lang4',
  'Lang5',
  'Abort',
  'Props',
  'NumpadParenLeft',
  'NumpadParenRight',
  'NumpadBackspace',
  'NumpadMemoryStore',
  'NumpadMemoryRecall',
  'NumpadMemoryClear',
  'NumpadMemoryAdd',
  'NumpadMemorySubtract',
  'NumpadClear',
  'NumpadClearEntry',
  'ControlLeft',
  'ShiftLeft',
  'AltLeft',
  'MetaLeft',
  'ControlRight',
  'ShiftRight',
  'AltRight',
  'MetaRight',
  'BrightnessUp',
  'BrightnessDown',
  'MediaPlay',
  'MediaRecord',
  'MediaFastForward',
  'MediaRewind',
  'MediaTrackNext',
  'MediaTrackPrevious',
  'MediaStop',
  'Eject',
  'MediaPlayPause',
  'MediaSelect',
  'LaunchMail',
  'LaunchApp2',
  'LaunchApp1',
  'SelectTask',
  'LaunchScreenSaver',
  'BrowserSearch',
  'BrowserHome',
  'BrowserBack',
  'BrowserForward',
  'BrowserStop',
  'BrowserRefresh',
  'BrowserFavorites',
  'ZoomToggle',
  'MailReply',
  'MailForward',
  'MailSend',
];

export namespace ScanCodeUtils {
  export function toString(scanCode: ScanCode): string {
    return ScanCodeToStr[scanCode] || String(scanCode);
  }
  export function fromString(code: string): ScanCode {
    const index = ScanCodeToStr.indexOf(code);
    return index !== -1 ? index : ScanCode.None;
  }
}
