name: MacOS Build

on:
  push:
    branches: [main]
    paths: &paths
      - 'src/**'
      - 'electron-builder.yml'
      - 'electron.vite.config.ts'
      - 'tsconfig.*.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths: *paths
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install macOS dependencies
        run: |
          brew install gnu-tar coreutils

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Compile
        run: pnpm exec electron-builder --mac -p never

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: atlas-macos
          path: dist/*
